seed: 42
device: cuda_if_available
batch_size: 16
num_workers: 2
num_epochs_feature_extraction: 2
num_epochs_fine_tuning: 2
optimizer: adam
lr_feature_extraction: 1e-3
lr_fine_tuning: 1e-4
weight_decay: 1e-4
pretrained_backbone: resnet18
freeze_until: layer4
log_dir: outputs/reports
fig_dir: outputs/figures
save_dir: models
dataset_name: cifar10
data_root: data/raw
download_dataset: true
train_subset_fraction: 0.05
val_subset_fraction: 0.1
max_train_samples: 1024
max_val_samples: 512
